export const STORE_USER = 'STORE_USER'
export const GET_ITEMS = 'GET_ITEMS'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const SET_OPENABLE = 'SET_OPENABLE'
export const DELETE_ITEM = 'DELETE_ITEM'
export const ADD_ITEM = 'ADD_ITEM'